theme: jekyll-theme-hacker
title: Militerm
author: jim
description: |
  A storytelling MUD engine in Elixir.
show_downloads: true
permalink: /:categories/:year/:month/:day/:title:output_ext
github:
  zip_url: "https://github.com/jgsmith/militerm/zipball/master"
  tar_url: "https://github.com/jgsmith/militerm/tarball/master"
exclude:
  - CNAME
