version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /app/assets/node_modules
      - /app/_build
      - .:/app
  postgres:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wlc_engine_dev
      POSTGRES_PASSWORD: postgres